CREATE TABLE sys_vod
(
    type_id       INTEGER NOT NULL,
    type_name     VARCHAR(255),
    vod_en        VARCHAR(255),
    vod_id        INTEGER NOT NULL,
    vod_name      VARCHAR(255),
    vod_play_from VARCHAR(255),
    vod_remarks   VARCHAR(100),
    vod_time      DATETIME,
    PRIMARY KEY (`vod_id`)
);
CREATE TABLE sys_vod_detail
(
    group_id           INTEGER,
    type_id            INTEGER,
    type_id_1          INTEGER,
    type_name          VARCHAR(100),
    vod_actor          VARCHAR(100),
    vod_area           VARCHAR(100),
    vod_author         VARCHAR(100),
    vod_behind         VARCHAR(100),
    vod_blurb          VARCHAR(100),
    vod_class          VARCHAR(100),
    vod_color          VARCHAR(100),
    vod_content        VARCHAR(255),
    vod_copyright      INTEGER,
    vod_director       VARCHAR(255),
    vod_douban_id      INTEGER,
    vod_douban_score   VARCHAR(255),
    vod_down           INTEGER,
    vod_down_from      VARCHAR(255),
    vod_down_note      VARCHAR(255),
    vod_down_server    VARCHAR(255),
    vod_down_url       VARCHAR(255),
    vod_duration       VARCHAR(255),
    vod_en             VARCHAR(255),
    vod_hits           INTEGER,
    vod_hits_day       INTEGER,
    vod_hits_month     INTEGER,
    vod_hits_week      INTEGER,
    vod_id             INTEGER,
    vod_isend          INTEGER,
    vod_jumpurl        VARCHAR(255),
    vod_lang           VARCHAR(255),
    vod_letter         VARCHAR(255),
    vod_level          INTEGER,
    vod_lock           INTEGER,
    vod_name           VARCHAR(255),
    vod_pic            VARCHAR(255),
    vod_pic_screenshot VARCHAR(255),
    vod_pic_slide      VARCHAR(255),
    vod_pic_thumb      VARCHAR(255),
    vod_play_from      VARCHAR(255),
    vod_play_note      VARCHAR(255),
    vod_play_server    VARCHAR(255),
    vod_play_url       VARCHAR(1000),
    vod_plot           INTEGER,
    vod_plot_detail    VARCHAR(255),
    vod_plot_name      VARCHAR(255),
    vod_points         INTEGER,
    vod_points_down    INTEGER,
    vod_points_play    INTEGER,
    vod_pubdate        VARCHAR(255),
    vod_pwd            VARCHAR(255),
    vod_pwd_down       VARCHAR(255),
    vod_pwd_down_url   VARCHAR(255),
    vod_pwd_play       VARCHAR(255),
    vod_pwd_play_url   VARCHAR(255),
    vod_pwd_url        VARCHAR(255),
    vod_rel_art        VARCHAR(255),
    vod_rel_vod        VARCHAR(255),
    vod_remarks        VARCHAR(255),
    vod_reurl          VARCHAR(255),
    vod_score          VARCHAR(255),
    vod_score_all      INTEGER,
    vod_score_num      INTEGER,
    vod_serial         VARCHAR(255),
    vod_state          VARCHAR(255),
    vod_status         INTEGER,
    vod_sub            VARCHAR(255),
    vod_tag            VARCHAR(255),
    vod_time           DATETIME,
    vod_time_add       INTEGER,
    vod_time_hits      INTEGER,
    vod_time_make      INTEGER,
    vod_total          INTEGER,
    vod_tpl            VARCHAR(255),
    vod_tpl_down       VARCHAR(255),
    vod_tpl_play       VARCHAR(255),
    vod_trysee         INTEGER,
    vod_tv             VARCHAR(255),
    vod_up             INTEGER,
    vod_version        VARCHAR(255),
    vod_weekday        VARCHAR(255),
    vod_writer         VARCHAR(255),
    vod_year           VARCHAR(255),
    PRIMARY KEY (vod_id)
);






